/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'growatt adapter settings': {
    en: 'Adapter settings for growatt',
    de: 'Adaptereinstellungen für growatt',
    ru: 'Настройки адаптера для growatt',
    pt: 'Configurações do adaptador para growatt',
    nl: 'Adapterinstellingen voor growatt',
    fr: "Paramètres d'adaptateur pour growatt",
    it: "Impostazioni dell'adattatore per growatt",
    es: 'Ajustes del adaptador para growatt',
    pl: 'Ustawienia adaptera dla growatt',
    'zh-cn': 'growatt的适配器设置',
  },
  'Login with shared key': {
    en: 'Login with shared key',
    de: 'Melden Sie sich mit dem freigegebenen Schlüssel an',
    ru: 'Войти с общим ключом',
    pt: 'Login com chave compartilhada',
    nl: 'Login met gedeelde sleutel',
    fr: 'Connexion avec clé partagée',
    it: 'Accedi con chiave condivisa',
    es: 'Iniciar sesión con clave compartida',
    pl: 'Zaloguj się za pomocą klucza wspólnego',
    'zh-cn': '使用共享密钥登录',
  },
  User: {
    en: 'User',
    de: 'Benutzer',
    ru: 'Пользователь',
    pt: 'Do utilizador',
    nl: 'Gebruiker',
    fr: 'Utilisateur',
    it: 'Utente',
    es: 'Usuario',
    pl: 'Użytkownik',
    'zh-cn': '用户',
  },
  Password: {
    en: 'Password',
    de: 'Passwort',
    ru: 'пароль',
    pt: 'Senha',
    nl: 'Wachtwoord',
    fr: 'Mot de passe',
    it: "Parola d'ordine",
    es: 'Contraseña',
    pl: 'Hasło',
    'zh-cn': '密码',
  },
  'The key from shared URL': {
    en: 'The key from shared URL',
    de: 'Der Schlüssel von der freigegebenen URL',
    ru: 'Ключ из общего URL',
    pt: 'A chave do URL compartilhado',
    nl: 'De sleutel van gedeelde URL',
    fr: "La clé de l'URL partagée",
    it: "La chiave dall'URL condiviso",
    es: 'La clave de la URL compartida',
    pl: 'Klucz z udostępnionego adresu URL',
    'zh-cn': '共享URL中的密钥',
  },
  'Read weather': {
    en: 'Read weather',
    de: 'Wetter lesen',
    ru: 'Читать погоду',
    pt: 'Leia o tempo',
    nl: 'Lees het weer',
    fr: 'Lire la météo',
    it: 'Leggi il meteo',
    es: 'Leer el tiempo',
    pl: 'Czytaj pogodę',
    'zh-cn': '阅读天气',
  },
  'Read device data': {
    en: 'Read device data',
    de: 'Gerätedaten lesen',
    ru: 'Прочитать данные устройства',
    pt: 'Leia os dados do dispositivo',
    nl: 'Lees apparaatgegevens',
    fr: "Lire les données de l'appareil",
    it: 'Leggi i dati del dispositivo',
    es: 'Leer datos del dispositivo',
    pl: 'Czytaj dane urządzenia',
    'zh-cn': '读取设备数据',
  },
  'Read total data': {
    en: 'Read total data',
    de: 'Gesamtdaten lesen',
    ru: 'Прочитать общие данные',
    pt: 'Leia os dados totais',
    nl: 'Lees de totale gegevens',
    fr: 'Lire les données totales',
    it: 'Leggi i dati totali',
    es: 'Leer datos totales',
    pl: 'Przeczytaj wszystkie dane',
    'zh-cn': '读取总数据',
  },
  'Read status data (not INV/MAX/TLX)': {
    en: 'Read status data (not INV/MAX/TLX)',
    de: 'Statusdaten lesen (nicht INV/MAX/TLX)',
    ru: 'Считывание данных состояния (не INV/MAX/TLX)',
    pt: 'Ler dados de status (não INV/MAX/TLX)',
    nl: 'Lees statusgegevens (niet INV/MAX/TLX)',
    fr: "Lire les données d'état (pas INV/MAX/TLX)",
    it: 'Leggere i dati di stato (non INV/MAX/TLX)',
    es: 'Leer datos de estado (no INV/MAX/TLX)',
    pl: 'Czytaj dane o stanie (nie INV/MAX/TLX)',
    'zh-cn': '读取状态数据（非INV/MAX/TLX）',
  },
  'Read last history data': {
    en: 'Read last history data',
    de: 'Lesen Sie die letzten Verlaufsdaten',
    ru: 'Прочитать последние данные истории',
    pt: 'Leia os últimos dados do histórico',
    nl: 'Lees de laatste geschiedenisgegevens',
    fr: "Lire les dernières données d'historique",
    it: 'Leggi gli ultimi dati della cronologia',
    es: 'Leer los últimos datos del historial',
    pl: 'Przeczytaj ostatnie dane historyczne',
    'zh-cn': '读取最近的历史数据',
  },
  'Read last data of chart (only INV/MAX/TLX) [deprecated]': {
    en: 'Read last data of chart (only INV/MAX/TLX) [deprecated]',
    de: 'Letzte Daten des Diagramms lesen (nur INV / MAX / TLX) [veraltet]',
    ru: 'Чтение последних данных диаграммы (только INV / MAX / TLX) [устарело]',
    pt: 'Ler os últimos dados do gráfico (apenas INV / MAX / TLX) [obsoleto]',
    nl: 'Laatste gegevens van diagram lezen (alleen INV / MAX / TLX) [verouderd]',
    fr: 'Lire les dernières données du graphique (uniquement INV / MAX / TLX) [obsolète]',
    it: 'Leggi gli ultimi dati del grafico (solo INV / MAX / TLX) [obsoleto]',
    es: 'Leer los últimos datos del gráfico (solo INV / MAX / TLX) [obsoleto]',
    pl: 'Przeczytaj ostatnie dane wykresu (tylko INV / MAX / TLX) [wycofane]',
    'zh-cn': '读取图表的最后数据（仅INV / MAX / TLX）[不建议使用]',
  },
  'Read data of chart (requires read last data of chart) [deprecated]': {
    en: 'Read data of chart (requires read last data of chart) [deprecated]',
    de: 'Daten des Diagramms lesen (erfordert das Lesen der letzten Daten des Diagramms) [veraltet]',
    ru: 'Чтение данных диаграммы (требуется чтение последних данных диаграммы) [устарело]',
    pt: 'Ler os dados do gráfico (requer a leitura dos últimos dados do gráfico) [obsoleto]',
    nl: 'Gegevens van diagram lezen (vereist laatste gegevens van diagram lezen) [verouderd]',
    fr: 'Lire les données du graphique (nécessite la lecture des dernières données du graphique) [obsolète]',
    it: 'Leggi i dati del grafico (richiede la lettura degli ultimi dati del grafico) [obsoleto]',
    es: 'Leer datos del gráfico (requiere leer los últimos datos del gráfico) [obsoleto]',
    pl: 'Odczytaj dane wykresu (wymaga odczytu ostatnich danych wykresu) [przestarzałe]',
    'zh-cn': '读取图表数据（需要读取图表的最后数据）[不建议使用]',
  },
  'Read plant data': {
    en: 'Read plant data',
    de: 'Anlagendaten lesen',
    ru: 'Прочитать данные о заводе',
    pt: 'Leia os dados da planta',
    nl: 'Lees installatiegegevens',
    fr: "Lire les données de l'installation",
    it: "Leggere i dati dell'impianto",
    es: 'Leer datos de la planta',
    pl: 'Przeczytaj dane zakładu',
    'zh-cn': '读取工厂数据',
  },
  normal: {
    en: 'normal',
    de: 'normal',
    ru: 'нормальный',
    pt: 'normal',
    nl: 'normaal',
    fr: 'Ordinaire',
    it: 'normale',
    es: 'normal',
    pl: 'normalna',
    'zh-cn': '正常',
  },
  delete: {
    en: 'delete',
    de: 'löschen',
    ru: 'Удалить',
    pt: 'excluir',
    nl: 'verwijderen',
    fr: 'effacer',
    it: 'Elimina',
    es: 'Eliminar',
    pl: 'usunąć',
    'zh-cn': '删除',
  },
  noupdate: {
    en: 'no update',
    de: 'kein Update',
    ru: 'нет обновления',
    pt: 'sem atualização',
    nl: 'geen update',
    fr: 'Pas de mise à jour',
    it: 'nessun aggiornamento',
    es: 'ninguna actualización',
    pl: 'brak aktualizacji',
    'zh-cn': '没有更新',
  },
  'Main Settings': {
    en: 'Main Settings',
    de: 'Haupteinstellungen',
    ru: 'Основные параметры',
    pt: 'Configurações principais',
    nl: 'Belangrijkste instellingen',
    fr: 'Réglages principaux',
    it: 'Impostazioni principali',
    es: 'Ajustes principales',
    pl: 'Ustawienia główne',
    'zh-cn': '主要设定',
  },
  'Manage Objects': {
    en: 'Manage Objects',
    de: 'Objekte verwalten',
    ru: 'Управлять объектами',
    pt: 'Gerenciar objetos',
    nl: 'Beheer objecten',
    fr: 'Gérer les objets',
    it: 'Gestisci oggetti',
    es: 'Administrar objetos',
    pl: 'Zarządzaj obiektami',
    'zh-cn': '管理物件',
  },
  Created: {
    en: 'Created',
    de: 'Erstellt',
    ru: 'Создано',
    pt: 'Criado',
    nl: 'Gemaakt',
    fr: 'Créé',
    it: 'Creato',
    es: 'Creado',
    pl: 'Utworzony',
    'zh-cn': '已建立',
  },
  Action: {
    en: 'Action',
    de: 'Aktion',
    ru: 'Действие',
    pt: 'Açao',
    nl: 'Actie',
    fr: 'action',
    it: 'Azione',
    es: 'Acción',
    pl: 'Akcja',
    'zh-cn': '行动',
  },
  Name: {
    en: 'Name',
    de: 'Name',
    ru: 'имя',
    pt: 'Nome',
    nl: 'Naam',
    fr: 'Nom',
    it: 'Nome',
    es: 'Nombre',
    pl: 'Nazwa',
    'zh-cn': '名称',
  },
  Type: {
    en: 'Type',
    de: 'Typ',
    ru: 'Тип',
    pt: 'Tipo',
    nl: 'Type',
    fr: 'Type',
    it: 'genere',
    es: 'Tipo',
    pl: 'Rodzaj',
    'zh-cn': '类型',
  },
  'Process timeout in seconds': {
    en: 'Process timeout in seconds',
    de: 'Prozess-Timeout in Sekunden',
    ru: 'Время ожидания процесса в секундах',
    pt: 'Tempo limite do processo em segundos',
    nl: 'Verwerkingstime-out in seconden',
    fr: "Délai d'attente du processus en secondes",
    it: 'Timeout del processo in secondi',
    es: 'Tiempo de espera del proceso en segundos',
    pl: 'Limit czasu procesu w sekundach',
    'zh-cn': '处理超时（以秒为单位）',
  },
  'Timeout in seconds': {
    en: 'Timeout in seconds',
    de: 'Zeitüberschreitung in Sekunden',
    ru: 'Время ожидания в секундах',
    pt: 'Tempo limite em segundos',
    nl: 'Time-out in seconden',
    fr: "Délai d'attente en secondes",
    it: 'Timeout in secondi',
    es: 'Tiempo de espera en segundos',
    pl: 'Limit czasu w sekundach',
    'zh-cn': '以秒为单位的超时',
  },
  'Keep web session': {
    en: 'Keep web session',
    de: 'Websitzung beibehalten',
    ru: 'Сохранить веб-сессию',
    pt: 'Manter sessão da web',
    nl: 'Websessie behouden',
    fr: 'Conserver la session Web',
    it: 'Mantieni la sessione web',
    es: 'Mantener sesión web',
    pl: 'Zachowaj sesję internetową',
    'zh-cn': '保持网络会话',
  },
  'Session time in minutes': {
    en: 'Session time in minutes',
    de: 'Sitzungszeit in Minuten',
    ru: 'Время сеанса в минутах',
    pt: 'Tempo de sessão em minutos',
    nl: 'Sessietijd in minuten',
    fr: 'Durée de la session en minutes',
    it: 'Durata della sessione in minuti',
    es: 'Tiempo de sesión en minutos',
    pl: 'Czas sesji w minutach',
    'zh-cn': '会话时间（分钟）',
  },
  'Cycle time in seconds': {
    en: 'Cycle time in seconds',
    de: 'Zykluszeit in Sekunden',
    ru: 'Время цикла в секундах',
    pt: 'Tempo de ciclo em segundos',
    nl: 'Cyclustijd in seconden',
    fr: 'Temps de cycle en secondes',
    it: 'Tempo di ciclo in secondi',
    es: 'Tiempo de ciclo en segundos',
    pl: 'Czas cyklu w sekundach',
    'zh-cn': '以秒为单位的周期时间',
  },
  'Error cycle time in seconds': {
    en: 'Error cycle time in seconds',
    de: 'Fehlerzykluszeit in Sekunden',
    ru: 'Время цикла ошибки в секундах',
    pt: 'Tempo de ciclo de erro em segundos',
    nl: 'Foutcyclustijd in seconden',
    fr: "Temps de cycle d'erreur en secondes",
    it: "Tempo di ciclo dell'errore in secondi",
    es: 'Tiempo de ciclo de error en segundos',
    pl: 'Czas cyklu błędu w sekundach',
    'zh-cn': '错误循环时间（以秒为单位）',
  },
  Datalogger: {
    en: 'Datalogger',
    de: 'Datenlogger',
    ru: 'Datalogger',
    pt: 'Datalogger',
    nl: 'Datalogger',
    fr: 'Datalogger',
    it: 'Datalogger',
    es: 'Datalogger',
    pl: 'Datalogger',
    'zh-cn': '数据摘要',
  },
  'Manage Dataloggers': {
    en: 'Manage Dataloggers',
    de: 'Datenlogger verwalten',
    ru: 'Управление Dataloggers',
    pt: 'Gerenciar Dataloggers',
    nl: 'Manage Dataloggers',
    fr: 'Gérer les enregistreurs de données',
    it: 'Gestione dei Datalogger',
    es: 'Manage Dataloggers',
    pl: 'Manage Datalog',
    'zh-cn': 'B. 管理数据目录',
  },
  'PV plant id': {
    en: 'PV plant id',
    de: 'PV-Anlage',
    ru: 'PV завод ид',
    pt: 'Planta de PV',
    nl: 'PV plant',
    fr: 'PV plant id',
    it: 'Impianti fotovoltaici',
    es: 'PV planta id',
    pl: 'Plant id (ang.)',
    'zh-cn': '电厂',
  },
  'PV plant name': {
    en: 'PV plant name',
    de: 'PV-Anlagenname',
    ru: 'PV название растения',
    pt: 'Nome da planta PV',
    nl: 'PV plant',
    fr: 'Nom de la plante PV',
    it: 'Nome impianto fotovoltaico',
    es: 'Nombre de planta PV',
    pl: 'Nazwa rośliny PV',
    'zh-cn': '电厂名称',
  },
  'Account name': {
    en: 'Account name',
    de: 'Name des Kontos',
    ru: 'Имя аккаунта',
    pt: 'Nome da conta',
    nl: 'Account naam',
    fr: 'Nom du compte',
    it: 'Nome account',
    es: 'Nombre de la cuenta',
    pl: 'Nazwa',
    'zh-cn': '名称',
  },
  'Serial number': {
    en: 'Serial number',
    de: 'Seriennummer',
    ru: 'Серийный номер',
    pt: 'Número de série',
    nl: 'Serienummer',
    fr: 'Numéro de série',
    it: 'Numero di serie',
    es: 'Número de serie',
    pl: 'Numer szeregowy',
    'zh-cn': '数量',
  },
  Alias: {
    en: 'Alias',
    de: 'Alias',
    ru: 'Алиас',
    pt: 'Alias',
    nl: 'Alias',
    fr: 'Alias',
    it: 'Alias',
    es: 'Alias',
    pl: 'Alias',
    'zh-cn': 'Aliasasas',
  },
  'Firmware version': {
    en: 'Firmware version',
    de: 'Firmware-Version',
    ru: 'Версия прошивки',
    pt: 'Versão de firmware',
    nl: 'Firmware',
    fr: 'Firmware version',
    it: 'Versione firmware',
    es: 'Versión de firmware',
    pl: 'Okładka',
    'zh-cn': '导 言',
  },
  'Device type index': {
    en: 'Device type index',
    de: 'Gerätetyp Index',
    ru: 'Тип устройства индекс',
    pt: 'Índice do tipo de dispositivo',
    nl: 'Vernietigingstype',
    fr: 'Indice de type de dispositif',
    it: 'Indice del tipo di dispositivo',
    es: 'Índice de tipo de dispositivo',
    pl: 'Indeks typowy',
    'zh-cn': '传单',
  },
  'Device type': {
    en: 'Device type',
    de: 'Gerätetyp',
    ru: 'Тип устройства',
    pt: 'Tipo de dispositivo',
    nl: 'Device type',
    fr: 'Type de dispositif',
    it: 'Tipo di dispositivo',
    es: 'Tipo de dispositivo',
    pl: 'Device type',
    'zh-cn': '2. 证人类型',
  },
  'Wifi model': {
    en: 'Wifi model',
    de: 'Wifi Modell',
    ru: 'Модель Wifi',
    pt: 'Modelo Wifi',
    nl: 'Wifi model',
    fr: 'Modèle Wifi',
    it: 'Modello Wifi',
    es: 'Modelo Wifi',
    pl: 'Wifi model',
    'zh-cn': '菲菲菲图',
  },
  'Comunication lost': {
    en: 'Comunication lost',
    de: 'Komunikation verloren',
    ru: 'Взаимодействие потеряно',
    pt: 'Comunidade perdida',
    nl: 'Comunicatie verloren',
    fr: 'Comunication lost',
    it: 'Comunicato perso',
    es: 'Comunication lost',
    pl: 'Comunicja przegrała',
    'zh-cn': '损失',
  },
  'Wifi signal level': {
    en: 'Wifi signal level',
    de: 'Wifi Signalpegel',
    ru: 'Уровень сигнала Wifi',
    pt: 'Nível de sinal Wifi',
    nl: 'Wifi signaal',
    fr: 'Niveau du signal Wifi',
    it: 'Livello del segnale Wifi',
    es: 'Nivel de señal Wifi',
    pl: 'Poziom Wifi',
    'zh-cn': '维菲信号水平',
  },
  'IP and port': {
    en: 'IP and port',
    de: 'IP und Port',
    ru: 'IP и порт',
    pt: 'IP e porta',
    nl: 'IP en haven',
    fr: 'IP et port',
    it: 'IP e porta',
    es: 'IP y puerto',
    pl: 'IP i port',
    'zh-cn': 'IP和港口',
  },
  Interval: {
    en: 'Interval',
    de: 'Intervall',
    ru: 'интервал',
    pt: 'Intervalo',
    nl: 'Interval',
    fr: 'Intervalle',
    it: 'Intervallo',
    es: 'Intervalo',
    pl: 'długość',
    'zh-cn': '间隔',
  },
  'Last update timepoint': {
    en: 'Last update timepoint',
    de: 'Letzter Update-Zeitpunkt',
    ru: 'Последнее обновление timepoint',
    pt: 'Última atualização',
    nl: 'Laatste update',
    fr: 'Dernière mise à jour',
    it: 'Ultimo aggiornamento',
    es: 'Último punto de tiempo de actualización',
    pl: 'Czasoprzestrzeń',
    'zh-cn': '上次更新时间',
  },
  'Server ip': {
    en: 'Server ip',
    de: 'Server ip',
    ru: 'Сервер ip',
    pt: 'Ip do servidor',
    nl: 'Server ip',
    fr: 'Server ip',
    it: 'Server ip',
    es: 'Servidor ip',
    pl: 'Serwer',
    'zh-cn': '导 言',
  },
  'Server port': {
    en: 'Server port',
    de: 'Serverport',
    ru: 'Порт сервера',
    pt: 'Porta do servidor',
    nl: 'Server haven',
    fr: 'Port de serveur',
    it: 'Porta server',
    es: 'Puerto servidor',
    pl: 'Porter',
    'zh-cn': '服务港口',
  },
  'Check firmware': {
    en: 'Check firmware',
    de: 'Firmware überprüfen',
    ru: 'Проверить прошивку',
    pt: 'Verificar firmware',
    nl: 'Controleer firmaware',
    fr: 'Vérifiez le firmware',
    it: 'Controllare il firmware',
    es: 'Comprobar firmware',
    pl: 'Oprogramowanie Check',
    'zh-cn': '检查公司',
  },
  'Restart datalogger': {
    en: 'Restart datalogger',
    de: 'Restart Datenlogger',
    ru: 'Перезапустите datalogger',
    pt: 'Reinicie o datalogger',
    nl: 'Herstart datalog',
    fr: 'Restart datalogger',
    it: 'Riavviare il datalogger',
    es: 'Restart datalogger',
    pl: 'Restart datalog',
    'zh-cn': '重开数据',
  },
  'Please enter new interval in minutes': {
    en: 'Please enter new interval in minutes',
    de: 'Bitte geben Sie ein neues Intervall in Minuten ein',
    ru: 'Пожалуйста, введите новый интервал за считанные минуты',
    pt: 'Digite um novo intervalo em minutos',
    nl: 'Kom binnen enkele minuten een nieuwe interval binnen',
    fr: 'Veuillez entrer un nouvel intervalle en quelques minutes',
    it: 'Si prega di inserire un nuovo intervallo in minuti',
    es: 'Por favor, introduzca el intervalo nuevo en minutos',
    pl: 'Przyjmuje się do nowej przerwy',
    'zh-cn': '请以新的分钟内间隔发言',
  },
  'Please enter new IP for server': {
    en: 'Please enter new IP for server',
    de: 'Bitte geben Sie eine neue IP für den Server ein',
    ru: 'Пожалуйста, введите новый IP для сервера',
    pt: 'Digite novo IP para servidor',
    nl: 'Betreed nieuwe IP voor server',
    fr: 'Veuillez saisir une nouvelle IP pour serveur',
    it: 'Inserisci il nuovo IP per il server',
    es: 'Por favor, introduzca IP nueva para servidor',
    pl: 'Wstęp do nowego serwera',
    'zh-cn': '请提供新的服务对象。',
  },
  'Please enter new port for server': {
    en: 'Please enter new port for server',
    de: 'Bitte geben Sie einen neuen Port für den Server ein',
    ru: 'Пожалуйста, введите новый порт для сервера',
    pt: 'Digite nova porta para servidor',
    nl: 'Kom binnen voor een server',
    fr: 'Veuillez entrer un nouveau port pour serveur',
    it: 'Inserisci una nuova porta per il server',
    es: 'Por favor introduzca nuevo puerto para servidor',
    pl: 'Wstęp do nowego portu dla serwera',
    'zh-cn': '请进入新的服务器港口',
  },
  "The server's response": {
    en: "The server's response",
    de: 'Antwort des Servers',
    ru: 'Ответ сервера',
    pt: 'Resposta do servidor',
    nl: 'De reactie van de server',
    fr: 'Réponse du serveur',
    it: 'La risposta del server',
    es: 'Respuesta del servidor',
    pl: 'Odpowiedź serwera',
    'zh-cn': '服务器的答复',
  },
  'The server did not respond to the request!': {
    en: 'The server did not respond to the request!',
    de: 'Der Server reagierte nicht auf die Anfrage!',
    ru: 'Сервер не ответил на запрос!',
    pt: 'O servidor não respondeu à solicitação!',
    nl: 'De server reageerde niet op het verzoek!',
    fr: "Le serveur n'a pas répondu à la demande !",
    it: 'Il server non ha risposto alla richiesta!',
    es: '¡El servidor no respondió a la solicitud!',
    pl: 'Serwer nie odpowiedział na prośbę!',
    'zh-cn': '服务器没有对请求作出反应!',
  },
  'The instance must be running and logged in to the server. Then the settings of the data logger can be called up via the refresh button in this tab.':
    {
      en: 'The instance must be running and logged in to the server. Then the settings of the data logger can be called up via the refresh button in this tab.',
      de: 'Die Instanz muss laufen und am Server eingeloggt sein. Dann können die Einstellungen des Datenloggers über den Refresh-Button in dieser Registerkarte aufgerufen werden.',
      ru: 'Например, необходимо запустить и войти на сервер. Затем настройки логгера данных можно назвать через кнопку обновления в этой вкладке.',
      pt: 'A instância deve ser executada e registrada no servidor. Em seguida, as configurações do registrador de dados podem ser chamadas através do botão de atualização nesta guia.',
      nl: 'De instance moet worden gerend en ingelogd bij de server. Dan kunnen de gegevens logger worden opgeroepen via de verfrissende knop in deze rekening.',
      fr: "L'instance doit être activée et connectée au serveur. Ensuite, les paramètres du journal de données peuvent être appelés via le bouton de rafraîchissement dans cet onglet.",
      it: "L'istanza deve essere in esecuzione e l'accesso al server. Quindi le impostazioni del data logger possono essere richiamate tramite il pulsante di aggiornamento in questa scheda.",
      es: 'La instancia debe estar corriendo y conectado al servidor. A continuación, la configuración del registrador de datos se puede llamar a través del botón de actualización en esta pestaña.',
      pl: 'Przykład musi być uruchomiony i wylogowany w serwerze. Wtedy ustawienia loggera danych mogą być nazywane przez odświeżoną przycisk w tabeli.',
      'zh-cn': '例子必须是向服务器操作和标志。 数据标志的环境中可以通过这一表格的制冷剂来予以命名。.',
    },
  Offset: {
    en: 'Offset',
    de: 'Offset',
    ru: 'Офсет',
    pt: 'Desligado',
    nl: 'Vertaling:',
    fr: 'Offset',
    it: 'Offset',
    es: 'Offset',
    pl: 'Offset',
    'zh-cn': 'B. 排 排 排',
  },
  ID: {
    en: 'ID',
    de: 'ID',
    ru: 'КОД',
    pt: 'ID',
    nl: 'ID',
    fr: 'ID',
    it: 'ID',
    es: 'ID',
    pl: 'ID',
    'zh-cn': 'ID ID',
  },
  success: {
    en: 'success',
    de: 'erfolg',
    ru: 'успех',
    pt: 'sucesso',
    nl: 'succes',
    fr: 'succès',
    it: 'successo',
    es: 'éxito',
    pl: 'sukces',
    'zh-cn': '成功',
  },
  'no success': {
    en: 'no success',
    de: 'kein erfolg',
    ru: 'без успеха',
    pt: 'sem sucesso',
    nl: 'geen succes',
    fr: 'pas de succès',
    it: 'nessun successo',
    es: 'sin éxito',
    pl: 'bez powodzenia',
    'zh-cn': '没有成功',
  },
  'Growatt server default https://server.growatt.com': {
    en: 'Growatt server default https://server.growatt.com',
    de: 'Growatt Server Standard https://server.growatt.com',
    ru: 'Growatt сервер по умолчанию https://server.growatt.com',
    pt: 'Padrão do servidor Growatt https://server.growatt.com',
    nl: 'Growatt server default https://server.growatt.com',
    fr: 'Par défaut de serveur Growatt https://server.growatt.com',
    it: 'Predefinito server https://server.growatt.com',
    es: 'Por defecto del servidor Growatt https://server.growatt.com',
    pl: 'Serwer Growatny https://server.growatt.com',
    'zh-cn': 'Growatt服务器 https://server.growatt.com',
  },
  'Write inverter settings (only mix/tlx/tlxh)': {
    en: 'Write inverter settings (only mix/tlx/tlxh)',
    de: 'Invertereinstellungen schreiben (nur mix/tlx/tlxh)',
    ru: 'Напишите настройки инвертора (только mix/tlx/tlxh)',
    pt: 'Escreva configurações do inversor (somente mistura/tlx/tlxh)',
    nl: 'Schrijf inverter settings (only mix/tlx/tlxh)',
    fr: "Écrire des paramètres d'invertisseur (seulement mix/tlx/tlxh)",
    it: 'Scrivi impostazioni inverter (solo mix/tlx/tlxh)',
    es: 'Escribir configuración de inversor (sólo mix/tlx/tlxh)',
    pl: 'Write inverter (mix/tlx/tlxh)',
    uk: 'Настроювання інвертора (mix/tlx/tlxh)',
    'zh-cn': '不同环境的标志(mix/tlx/tlxh)',
  },
  'Reading and writing the inverter settings is at your own risk. It can damage the inverter. The functions have been tested to the best of our knowledge.':
    {
      en: 'Reading and writing the inverter settings is at your own risk. It can damage the inverter. The functions have been tested to the best of our knowledge.',
      de: 'Das Lesen und Schreiben der Wechselrichtereinstellungen erfolgt auf eigene Gefahr. Es kann den Wechselrichter beschädigen. Die Funktionen wurden nach bestem Wissen getestet.',
      ru: 'Чтение и написание настроек инвертора на вашем собственном риске. Он может повредить инвертор. Функции были проверены на лучшее из наших знаний.',
      pt: 'Ler e escrever as configurações do inversor está em seu próprio risco. Pode danificar o inversor. As funções foram testadas para o melhor de nosso conhecimento.',
      nl: 'Lezen en schrijven van de inverter settings is in je eigen risico. Het kan de inverter schaden. De functies zijn getest op het beste van onze kennis.',
      fr: "La lecture et l'écriture des paramètres de l'inverté sont à votre propre risque. Il peut endommager l'invertateur. Les fonctions ont été testées au mieux de nos connaissances.",
      it: "Leggere e scrivere le impostazioni dell'inverter è a proprio rischio. Può danneggiare l'inverter. Le funzioni sono state testate al meglio delle nostre conoscenze.",
      es: 'Leer y escribir la configuración del inversor está en su propio riesgo. Puede dañar el inversor. Las funciones han sido probadas al mejor de nuestros conocimientos.',
      pl: 'Czytanie i pisanie ustawienia inwerterów znajduje się na własnym ryzyku. Może uszkodzić inwersatora. Funkcje te zostały przetestowane na najlepszą wiedzę.',
      uk: 'Читання та написання параметрів інвертора на власний ризик. Це може пошкодити інвертор. Наші функції протестовані в кращих знаннях.',
      'zh-cn': '阅读和写信的环境中面临你本身的风险。 它会破坏多样性。 这些职能是对我们知识进行最佳测试的。.',
    },
  'Select it if your Growatt page is a black C and I page': {
    en: 'Select it if your Growatt page is a black C&I page',
    de: 'Wählen Sie es aus, wenn Ihre Growatt-Seite eine schwarze C&I-Seite ist',
    ru: 'Выберите его, если ваша страница Growatt является черной C & I страницы',
    pt: 'Selecioná-lo se sua página Growatt é uma página C&I preta',
    nl: 'Verkoop het als je Growat pagina een zwarte pagina is',
    fr: 'Sélectionnez-le si votre page Growatt est une page Cautorisation noire',
    it: 'Selezionalo se la pagina Growatt è una pagina C&I nera',
    es: 'Seleccione si su página de Growatt es una página de CENTE negro',
    pl: 'Wybiera go, jeśli twój profil jest czarnym stroną C&I',
    uk: 'Виберіть його, якщо ваша сторінка Growatt є чорною C&I сторінкою',
    'zh-cn': '如果你的Growatt页是黑白的C&I页。',
  },
};
