/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'growatt adapter settings': {
    en: 'Adapter settings for growatt',
    de: 'Adaptereinstellungen für growatt',
    ru: 'Настройки адаптера для growatt',
    pt: 'Configurações do adaptador para growatt',
    nl: 'Adapterinstellingen voor growatt',
    fr: "Paramètres d'adaptateur pour growatt",
    it: "Impostazioni dell'adattatore per growatt",
    es: 'Ajustes del adaptador para growatt',
    pl: 'Ustawienia adaptera dla growatt',
    'zh-cn': 'growatt的适配器设置',
  },
  'Login with shared key': {
    en: 'Login with shared key',
    de: 'Melden Sie sich mit dem freigegebenen Schlüssel an',
    ru: 'Войти с общим ключом',
    pt: 'Login com chave compartilhada',
    nl: 'Login met gedeelde sleutel',
    fr: 'Connexion avec clé partagée',
    it: 'Accedi con chiave condivisa',
    es: 'Iniciar sesión con clave compartida',
    pl: 'Zaloguj się za pomocą klucza wspólnego',
    'zh-cn': '使用共享密钥登录',
  },
  User: {
    en: 'User',
    de: 'Benutzer',
    ru: 'Пользователь',
    pt: 'Do utilizador',
    nl: 'Gebruiker',
    fr: 'Utilisateur',
    it: 'Utente',
    es: 'Usuario',
    pl: 'Użytkownik',
    'zh-cn': '用户',
  },
  Password: {
    en: 'Password',
    de: 'Passwort',
    ru: 'пароль',
    pt: 'Senha',
    nl: 'Wachtwoord',
    fr: 'Mot de passe',
    it: "Parola d'ordine",
    es: 'Contraseña',
    pl: 'Hasło',
    'zh-cn': '密码',
  },
  'The key from shared URL': {
    en: 'The key from shared URL',
    de: 'Der Schlüssel von der freigegebenen URL',
    ru: 'Ключ из общего URL',
    pt: 'A chave do URL compartilhado',
    nl: 'De sleutel van gedeelde URL',
    fr: "La clé de l'URL partagée",
    it: "La chiave dall'URL condiviso",
    es: 'La clave de la URL compartida',
    pl: 'Klucz z udostępnionego adresu URL',
    'zh-cn': '共享URL中的密钥',
  },
  'Read weather': {
    en: 'Read weather',
    de: 'Wetter lesen',
    ru: 'Читать погоду',
    pt: 'Leia o tempo',
    nl: 'Lees het weer',
    fr: 'Lire la météo',
    it: 'Leggi il meteo',
    es: 'Leer el tiempo',
    pl: 'Czytaj pogodę',
    'zh-cn': '阅读天气',
  },
  'Read device data': {
    en: 'Read device data',
    de: 'Gerätedaten lesen',
    ru: 'Прочитать данные устройства',
    pt: 'Leia os dados do dispositivo',
    nl: 'Lees apparaatgegevens',
    fr: "Lire les données de l'appareil",
    it: 'Leggi i dati del dispositivo',
    es: 'Leer datos del dispositivo',
    pl: 'Czytaj dane urządzenia',
    'zh-cn': '读取设备数据',
  },
  'Read total data': {
    en: 'Read total data',
    de: 'Gesamtdaten lesen',
    ru: 'Прочитать общие данные',
    pt: 'Leia os dados totais',
    nl: 'Lees de totale gegevens',
    fr: 'Lire les données totales',
    it: 'Leggi i dati totali',
    es: 'Leer datos totales',
    pl: 'Przeczytaj wszystkie dane',
    'zh-cn': '读取总数据',
  },
  'Read status data (not INV/MAX/TLX)': {
    en: 'Read status data (not INV/MAX/TLX)',
    de: 'Statusdaten lesen (nicht INV/MAX/TLX)',
    ru: 'Считывание данных состояния (не INV/MAX/TLX)',
    pt: 'Ler dados de status (não INV/MAX/TLX)',
    nl: 'Lees statusgegevens (niet INV/MAX/TLX)',
    fr: "Lire les données d'état (pas INV/MAX/TLX)",
    it: 'Leggere i dati di stato (non INV/MAX/TLX)',
    es: 'Leer datos de estado (no INV/MAX/TLX)',
    pl: 'Czytaj dane o stanie (nie INV/MAX/TLX)',
    'zh-cn': '读取状态数据（非INV/MAX/TLX）',
  },
  'Read last history data': {
    en: 'Read last history data',
    de: 'Lesen Sie die letzten Verlaufsdaten',
    ru: 'Прочитать последние данные истории',
    pt: 'Leia os últimos dados do histórico',
    nl: 'Lees de laatste geschiedenisgegevens',
    fr: "Lire les dernières données d'historique",
    it: 'Leggi gli ultimi dati della cronologia',
    es: 'Leer los últimos datos del historial',
    pl: 'Przeczytaj ostatnie dane historyczne',
    'zh-cn': '读取最近的历史数据',
  },
  'Read last data of chart (only INV/MAX/TLX) [deprecated]': {
    en: 'Read last data of chart (only INV/MAX/TLX) [deprecated]',
    de: 'Letzte Daten des Diagramms lesen (nur INV / MAX / TLX) [veraltet]',
    ru: 'Чтение последних данных диаграммы (только INV / MAX / TLX) [устарело]',
    pt: 'Ler os últimos dados do gráfico (apenas INV / MAX / TLX) [obsoleto]',
    nl: 'Laatste gegevens van diagram lezen (alleen INV / MAX / TLX) [verouderd]',
    fr: 'Lire les dernières données du graphique (uniquement INV / MAX / TLX) [obsolète]',
    it: 'Leggi gli ultimi dati del grafico (solo INV / MAX / TLX) [obsoleto]',
    es: 'Leer los últimos datos del gráfico (solo INV / MAX / TLX) [obsoleto]',
    pl: 'Przeczytaj ostatnie dane wykresu (tylko INV / MAX / TLX) [wycofane]',
    'zh-cn': '读取图表的最后数据（仅INV / MAX / TLX）[不建议使用]',
  },
  'Read data of chart (requires read last data of chart) [deprecated]': {
    en: 'Read data of chart (requires read last data of chart) [deprecated]',
    de: 'Daten des Diagramms lesen (erfordert das Lesen der letzten Daten des Diagramms) [veraltet]',
    ru: 'Чтение данных диаграммы (требуется чтение последних данных диаграммы) [устарело]',
    pt: 'Ler os dados do gráfico (requer a leitura dos últimos dados do gráfico) [obsoleto]',
    nl: 'Gegevens van diagram lezen (vereist laatste gegevens van diagram lezen) [verouderd]',
    fr: 'Lire les données du graphique (nécessite la lecture des dernières données du graphique) [obsolète]',
    it: 'Leggi i dati del grafico (richiede la lettura degli ultimi dati del grafico) [obsoleto]',
    es: 'Leer datos del gráfico (requiere leer los últimos datos del gráfico) [obsoleto]',
    pl: 'Odczytaj dane wykresu (wymaga odczytu ostatnich danych wykresu) [przestarzałe]',
    'zh-cn': '读取图表数据（需要读取图表的最后数据）[不建议使用]',
  },
  'Read plant data': {
    en: 'Read plant data',
    de: 'Anlagendaten lesen',
    ru: 'Прочитать данные о заводе',
    pt: 'Leia os dados da planta',
    nl: 'Lees installatiegegevens',
    fr: "Lire les données de l'installation",
    it: "Leggere i dati dell'impianto",
    es: 'Leer datos de la planta',
    pl: 'Przeczytaj dane zakładu',
    'zh-cn': '读取工厂数据',
  },
  normal: {
    en: 'normal',
    de: 'normal',
    ru: 'нормальный',
    pt: 'normal',
    nl: 'normaal',
    fr: 'Ordinaire',
    it: 'normale',
    es: 'normal',
    pl: 'normalna',
    'zh-cn': '正常',
  },
  delete: {
    en: 'delete',
    de: 'löschen',
    ru: 'Удалить',
    pt: 'excluir',
    nl: 'verwijderen',
    fr: 'effacer',
    it: 'Elimina',
    es: 'Eliminar',
    pl: 'usunąć',
    'zh-cn': '删除',
  },
  noupdate: {
    en: 'no update',
    de: 'kein Update',
    ru: 'нет обновления',
    pt: 'sem atualização',
    nl: 'geen update',
    fr: 'Pas de mise à jour',
    it: 'nessun aggiornamento',
    es: 'ninguna actualización',
    pl: 'brak aktualizacji',
    'zh-cn': '没有更新',
  },
  'Main Settings': {
    en: 'Main Settings',
    de: 'Haupteinstellungen',
    ru: 'Основные параметры',
    pt: 'Configurações principais',
    nl: 'Belangrijkste instellingen',
    fr: 'Réglages principaux',
    it: 'Impostazioni principali',
    es: 'Ajustes principales',
    pl: 'Ustawienia główne',
    'zh-cn': '主要设定',
  },
  'Manage Objects': {
    en: 'Manage Objects',
    de: 'Objekte verwalten',
    ru: 'Управлять объектами',
    pt: 'Gerenciar objetos',
    nl: 'Beheer objecten',
    fr: 'Gérer les objets',
    it: 'Gestisci oggetti',
    es: 'Administrar objetos',
    pl: 'Zarządzaj obiektami',
    'zh-cn': '管理物件',
  },
  Created: {
    en: 'Created',
    de: 'Erstellt',
    ru: 'Создано',
    pt: 'Criado',
    nl: 'Gemaakt',
    fr: 'Créé',
    it: 'Creato',
    es: 'Creado',
    pl: 'Utworzony',
    'zh-cn': '已建立',
  },
  Action: {
    en: 'Action',
    de: 'Aktion',
    ru: 'Действие',
    pt: 'Açao',
    nl: 'Actie',
    fr: 'action',
    it: 'Azione',
    es: 'Acción',
    pl: 'Akcja',
    'zh-cn': '行动',
  },
  Name: {
    en: 'Name',
    de: 'Name',
    ru: 'имя',
    pt: 'Nome',
    nl: 'Naam',
    fr: 'Nom',
    it: 'Nome',
    es: 'Nombre',
    pl: 'Nazwa',
    'zh-cn': '名称',
  },
  Type: {
    en: 'Type',
    de: 'Typ',
    ru: 'Тип',
    pt: 'Tipo',
    nl: 'Type',
    fr: 'Type',
    it: 'genere',
    es: 'Tipo',
    pl: 'Rodzaj',
    'zh-cn': '类型',
  },
  'Process timeout in seconds': {
    en: 'Process timeout in seconds',
    de: 'Prozess-Timeout in Sekunden',
    ru: 'Время ожидания процесса в секундах',
    pt: 'Tempo limite do processo em segundos',
    nl: 'Verwerkingstime-out in seconden',
    fr: "Délai d'attente du processus en secondes",
    it: 'Timeout del processo in secondi',
    es: 'Tiempo de espera del proceso en segundos',
    pl: 'Limit czasu procesu w sekundach',
    'zh-cn': '处理超时（以秒为单位）',
  },
  'Timeout in seconds': {
    en: 'Timeout in seconds',
    de: 'Zeitüberschreitung in Sekunden',
    ru: 'Время ожидания в секундах',
    pt: 'Tempo limite em segundos',
    nl: 'Time-out in seconden',
    fr: "Délai d'attente en secondes",
    it: 'Timeout in secondi',
    es: 'Tiempo de espera en segundos',
    pl: 'Limit czasu w sekundach',
    'zh-cn': '以秒为单位的超时',
  },
  'Keep web session': {
    en: 'Keep web session',
    de: 'Websitzung beibehalten',
    ru: 'Сохранить веб-сессию',
    pt: 'Manter sessão da web',
    nl: 'Websessie behouden',
    fr: 'Conserver la session Web',
    it: 'Mantieni la sessione web',
    es: 'Mantener sesión web',
    pl: 'Zachowaj sesję internetową',
    'zh-cn': '保持网络会话',
  },
  'Session time in minutes': {
    en: 'Session time in minutes',
    de: 'Sitzungszeit in Minuten',
    ru: 'Время сеанса в минутах',
    pt: 'Tempo de sessão em minutos',
    nl: 'Sessietijd in minuten',
    fr: 'Durée de la session en minutes',
    it: 'Durata della sessione in minuti',
    es: 'Tiempo de sesión en minutos',
    pl: 'Czas sesji w minutach',
    'zh-cn': '会话时间（分钟）',
  },
  'Cycle time in seconds': {
    en: 'Cycle time in seconds',
    de: 'Zykluszeit in Sekunden',
    ru: 'Время цикла в секундах',
    pt: 'Tempo de ciclo em segundos',
    nl: 'Cyclustijd in seconden',
    fr: 'Temps de cycle en secondes',
    it: 'Tempo di ciclo in secondi',
    es: 'Tiempo de ciclo en segundos',
    pl: 'Czas cyklu w sekundach',
    'zh-cn': '以秒为单位的周期时间',
  },
  'Error cycle time in seconds': {
    en: 'Error cycle time in seconds',
    de: 'Fehlerzykluszeit in Sekunden',
    ru: 'Время цикла ошибки в секундах',
    pt: 'Tempo de ciclo de erro em segundos',
    nl: 'Foutcyclustijd in seconden',
    fr: "Temps de cycle d'erreur en secondes",
    it: "Tempo di ciclo dell'errore in secondi",
    es: 'Tiempo de ciclo de error en segundos',
    pl: 'Czas cyklu błędu w sekundach',
    'zh-cn': '错误循环时间（以秒为单位）',
  },
};
